# Generated by Django 4.2.1 on 2023-05-22 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('concretado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Carrito de compras',
                'verbose_name_plural': 'Carrito',
                'db_table': 'carrito',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Categorias de los productos',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('exa', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Colores disponibles',
                'verbose_name_plural': 'Colores',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_comp', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=15)),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualtrends.carrito')),
            ],
            options={
                'verbose_name': 'Compras concretadas',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_con', models.AutoField(primary_key=True, serialize=False)),
                ('msj', models.TextField(max_length=1000)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.IntegerField(max_length=15)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Mensajes de los usuarios para contactar',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contacto',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_env', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Diferentes formas de envios',
                'verbose_name_plural': 'Envios',
                'db_table': 'envio',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Registro de emails para Newsletter',
                'verbose_name_plural': 'Newsletters',
                'db_table': 'newsletter',
            },
        ),
        migrations.CreateModel(
            name='Niveluser',
            fields=[
                ('id_lvl', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Nivel de usuario',
                'verbose_name_plural': 'Niveles de usuarios',
                'db_table': 'nivel_u',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Metodos de pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=200)),
                ('stock', models.IntegerField(max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('talle_personalizado', models.BooleanField(default=True)),
                ('eliminar', models.BooleanField(default=False)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualtrends.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id_talle', models.AutoField(primary_key=True, serialize=False)),
                ('inicial_talle', models.CharField(max_length=10)),
                ('medida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('m_h', models.BooleanField(verbose_name='True')),
            ],
            options={
                'verbose_name': 'Tallas de los productos',
                'verbose_name_plural': 'Tallas',
                'db_table': 'talla',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('tel_cel', models.IntegerField(max_length=20)),
                ('dir_calle', models.CharField(max_length=40)),
                ('dir_numero', models.IntegerField(max_length=7)),
                ('cp', models.IntegerField(max_length=7)),
                ('ciudad', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('ph', models.CharField(max_length=30)),
                ('id_lvl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualtrends.niveluser')),
            ],
            options={
                'verbose_name': 'Usuarios del sistema',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='TallesPersonalizados',
            fields=[
                ('id_per', models.AutoField(primary_key=True, serialize=False)),
                ('cuello', models.DecimalField(decimal_places=2, max_digits=10)),
                ('busto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('con_rodilla', models.DecimalField(decimal_places=2, max_digits=10)),
                ('larg_talle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('con_cintura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('con_cadera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('larg_manga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('con_muneca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('larg_pierna', models.DecimalField(decimal_places=2, max_digits=10)),
                ('altura_rodilla', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtrends.usuario')),
            ],
            options={
                'verbose_name': 'Talles Perzonalizados del Usuario',
                'verbose_name_plural': 'Talles Perzonalizados',
                'db_table': 'talle_per',
            },
        ),
        migrations.CreateModel(
            name='TallaDelProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtrends.productos')),
                ('id_talle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualtrends.talla')),
            ],
            options={
                'verbose_name': 'Tallas de cada Producto',
                'verbose_name_plural': 'Tallas de cada Producto',
                'db_table': 'prod_talla',
            },
        ),
        migrations.CreateModel(
            name='ProductosEnCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, max_length=4)),
                ('talla', models.IntegerField(default=1, max_length=7)),
                ('espersonalizado', models.BooleanField(default=False)),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtrends.carrito')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtrends.productos')),
            ],
            options={
                'verbose_name': 'Lista de los productos en los carritos',
                'verbose_name_plural': 'Productos en un Carrito',
                'db_table': 'prod_carrito',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('psw', models.CharField(max_length=30)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtrends.usuario')),
            ],
            options={
                'verbose_name': 'Usuario y contraseña para el login',
                'verbose_name_plural': 'Logeos',
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='ImagenesProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=150)),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtrends.productos')),
            ],
            options={
                'verbose_name': 'Imagenes de los Productos',
                'verbose_name_plural': 'Imagenes',
                'db_table': 'produc_img',
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtrends.usuario')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtrends.productos')),
            ],
            options={
                'verbose_name': 'Productos favoritos de cada usuario',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favorito',
            },
        ),
        migrations.CreateModel(
            name='EnvioDeCompras',
            fields=[
                ('cod_env', models.AutoField(primary_key=True, serialize=False)),
                ('destino_calle', models.CharField(max_length=30)),
                ('destino_numero', models.IntegerField(max_length=10)),
                ('id_comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualtrends.compras')),
                ('id_env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualtrends.envio')),
            ],
            options={
                'verbose_name': 'En de las compras concretadas',
                'verbose_name_plural': 'Compras',
                'db_table': 'envio_compra',
            },
        ),
        migrations.AddField(
            model_name='compras',
            name='id_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualtrends.pago'),
        ),
        migrations.CreateModel(
            name='ColoresProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtrends.colores')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtrends.productos')),
            ],
            options={
                'verbose_name': 'Colores de los Productos',
                'verbose_name_plural': 'Colores',
                'db_table': 'produc_color',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtrends.usuario'),
        ),
    ]
