# Generated by Django 4.2.1 on 2023-05-22 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualtrends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coloresproductos',
            options={'verbose_name': 'Colores de los Productos', 'verbose_name_plural': 'Colores de Producto'},
        ),
    ]
