# Generated by Django 4.2.1 on 2023-05-22 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualtrends', '0002_alter_coloresproductos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviodecompras',
            options={'verbose_name': 'En de las compras concretadas', 'verbose_name_plural': 'Envio de Compras'},
        ),
    ]
